version: '2.1'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app